on:
  push:
    branches:
      - main
    paths-ignore:
      - CHANGELOG.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn test:ts
      - run: yarn test:unit

  build:
    needs: test
    runs-on: ubuntu-latest
    concurrency:
      group: build
      cancel-in-progress: true
    outputs:
      continue: ${{ steps.version.outputs.continue }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - id: version
        run: echo "::set-output name=continue::$(yarn build:version)"
      - if: ${{ steps.version.outputs.continue == 'continue' }}
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  acceptance:
    needs: build
    if: ${{ needs.build.outputs.continue == 'continue' }}
    runs-on: ubuntu-latest
    concurrency:
      group: acceptance
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - run: ls -la
      - run: cat package.json
      - run: yarn test:acceptance

  publish:
    needs: acceptance
    runs-on: ubuntu-latest
    concurrency:
      group: publish
      cancel-in-progress: true
    env:
      INPUT_TOKEN: ""
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/package.json
          access: public
      - run: yarn build:tag
      - run: yarn changelog
      - uses: ad-m/github-push-action@master
        with:
          tags: true

  docs:
    needs: publish
    runs-on: ubuntu-latest
    concurrency:
      group: docs
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
